# Model Training

In [1]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix


In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv('heart_disease.csv')

In [3]:
df.head()

Unnamed: 0  male   age  education  currentSmoker  cigsPerDay  prevalentHyp  \
0           0   1.0  39.0        4.0            0.0         0.0           0.0   
1           1   0.0  46.0        2.0            0.0         0.0           0.0   
2           2   1.0  48.0        1.0            1.0        20.0           0.0   
3           3   0.0  61.0        3.0            1.0        30.0           1.0   
4           4   0.0  46.0        3.0            1.0        23.0           0.0   

   totChol  sysBP  diaBP    BMI  heartRate  glucose  TenYearCHD  
0    195.0  106.0   70.0  26.97       80.0     77.0           0  
1    250.0  121.0   81.0  28.73       95.0     76.0           0  
2    245.0  127.5   80.0  25.34       75.0     70.0           0  
3    225.0  150.0   95.0  28.58       65.0    103.0           1  
4    285.0  130.0   84.0  23.10       85.0     85.0           0

In [4]:
y=df.TenYearCHD

In [5]:
y

0       0
1       0
2       0
3       1
4       0
       ..
4233    1
4234    0
4235    0
4236    0
4237    0
Name: TenYearCHD, Length: 4238, dtype: int64

In [6]:
X = df.drop('TenYearCHD',axis=1)

In [7]:
X.head()

Unnamed: 0  male   age  education  currentSmoker  cigsPerDay  prevalentHyp  \
0           0   1.0  39.0        4.0            0.0         0.0           0.0   
1           1   0.0  46.0        2.0            0.0         0.0           0.0   
2           2   1.0  48.0        1.0            1.0        20.0           0.0   
3           3   0.0  61.0        3.0            1.0        30.0           1.0   
4           4   0.0  46.0        3.0            1.0        23.0           0.0   

   totChol  sysBP  diaBP    BMI  heartRate  glucose  
0    195.0  106.0   70.0  26.97       80.0     77.0  
1    250.0  121.0   81.0  28.73       95.0     76.0  
2    245.0  127.5   80.0  25.34       75.0     70.0  
3    225.0  150.0   95.0  28.58       65.0    103.0  
4    285.0  130.0   84.0  23.10       85.0     85.0

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.33,random_state = 41)

In [9]:
X_train.shape

(2839, 13)

In [10]:
X_test.shape

(1399, 13)

In [11]:
y_train.shape, y_test.shape

((2839,), (1399,))

In [12]:
logistic_reg = LogisticRegression()

In [13]:
logistic_reg.fit(X_train, y_train)

d:\srinu_babu_folder\python projects\Heart_disease\heart_disease_env\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [14]:
y_pred = logistic_reg.predict(X_test)

In [15]:
accuracy_score(y_test,y_pred)

0.8634739099356683

In [16]:
confusion_matrix(y_test,y_pred)

array([[1205,    4],
       [ 187,    3]], dtype=int64)

In [17]:
logistic_reg_1= LogisticRegression(penalty='l1',multi_class='ovr', solver='liblinear')
logistic_reg_1.fit(X_train, y_train)
y_pred_1 = logistic_reg_1.predict(X_test)
print(accuracy_score(y_test,y_pred_1))
print(confusion_matrix(y_test,y_pred_1))

0.8656182987848463
[[1202    7]
 [ 181    9]]


In [18]:
logistic_reg_2= LogisticRegression(penalty='l1',multi_class='ovr', solver='liblinear')
logistic_reg_2.fit(X_train, y_train)
y_pred_2 = logistic_reg_2.predict(X_test)
print(accuracy_score(y_test,y_pred_2))
print(confusion_matrix(y_test,y_pred_1))

0.8656182987848463
[[1202    7]
 [ 181    9]]


In [19]:
logistic_reg_2= LogisticRegression(penalty='elasticnet',multi_class='ovr', solver='saga',l1_ratio=0.1)
logistic_reg_2.fit(X_train, y_train)
y_pred_2 = logistic_reg_2.predict(X_test)
print(accuracy_score(y_test,y_pred_2))
print(confusion_matrix(y_test,y_pred_1))

0.8641887062187277
[[1202    7]
 [ 181    9]]


d:\srinu_babu_folder\python projects\Heart_disease\heart_disease_env\lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


## pipeline

In [21]:
from sklearn.pipeline import Pipeline